/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.City;
import Business.Network.Country;
import Business.Network.State;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UI.GuestWorkArea.GuestWorkAreaJPanel;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shalini
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    private JPanel rightpanel;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;
    public LoginJPanel(JPanel rightpanel, EcoSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.rightpanel = rightpanel;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        lblTitel = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        text_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_guestlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 248, 245));
        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_username.setText("User Name:");
        add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, -1));

        label_password.setText("Password:");
        add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        lblTitel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitel.setText("Health Plus");
        add(lblTitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 50));

        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 120, -1));
        add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 120, -1));

        btn_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 150, 30));

        btn_guestlogin.setBackground(new java.awt.Color(255, 255, 255));
        btn_guestlogin.setText("Sign in as Guest");
        btn_guestlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_guestlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guestloginActionPerformed(evt);
            }
        });
        add(btn_guestlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Health-professional-team.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 470, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-icon.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(235, 215));
        jLabel3.setMinimumSize(new java.awt.Dimension(235, 215));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 195));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 200, 200));

        jTextArea2.setBackground(new java.awt.Color(250, 246, 227));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("\n  Contact us:\n  Email address : medicaresystem@gmail.com");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 770, 360, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
         // Get user name
        String userName = text_username.getText();
        // Get Password
        char[] passwordCharArray = text_password.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        if(userName.equals("") || password.equals("")){
           JOptionPane.showMessageDialog(null, "Please enter values for user name and password", "Warning", JOptionPane.WARNING_MESSAGE);
           return; 
        }
        // validate username
        String regex = "^[a-z A-Z]+$";
        Pattern namePattern = Pattern.compile(regex);
        Matcher nameMatcher = namePattern.matcher(userName);
        
        if(!nameMatcher.matches()){
             JOptionPane.showMessageDialog(null, "Invalid characters in user name", "Warning", JOptionPane.WARNING_MESSAGE);
             return;
        }

        //step1: check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        
        Enterprise inEnterprise = null;
        Organization inOrganization = null;

            if(userAccount !=null && !(userAccount.getRole().getName().equals("Applicant Type") || userAccount.getUsername().equals("sys"))){
              // step 2: go inside each network and check each enterprise
                        for(Country network: system.getNetworkList()){
                            for(State s: network.getStateList()){
                                for(City c: s.getCityList()){
                                       //Step 2-a: Check against each enterprise
                                        for (Enterprise enterprise : c.getEnterpriseDirectory().getEnterpriseList()) {
                                            UserAccount ua_e = enterprise.getUserAccountDirectory().authenticateUser(userName, password); // sys admin
                                            
                                            if(ua_e != null){ // loop in onky if the user account is not null 
                                                if (ua_e.getUsername().equals(userAccount.getUsername()) &&
                                                    !ua_e.getRole().getName().equals("Admin Type")) {
                                                //Step3: Check against each organization inside that enterprise
                                                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                                    UserAccount ua = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                                    if (ua != null) {
                                                        inEnterprise = enterprise;
                                                        inOrganization = organization;
                                                        break;
                                                    }
                                                }
                                            } else {
                                                inEnterprise = enterprise;
                                                break;
                                            }
                                            if (inOrganization != null) {
                                                break;
                                            }
                                            }
                                            
                                        }

                                }    
                            }
                        }
            }
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "User name and password are case sensitive."
                    + "Enter valid credentials", "Warning", JOptionPane.WARNING_MESSAGE);
            text_username.setText("");
            text_password.setText("");
            return;
        }else{
            // clearing login fields
            text_username.setText("");
            text_password.setText("");
            CardLayout cardLayout = (CardLayout) rightpanel.getLayout();
            rightpanel.add("workArea",userAccount.getRole().createWorkArea(rightpanel, system, dB4OUtil, userAccount, inOrganization, inEnterprise));
            cardLayout.next(rightpanel);   
        }


    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_guestloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guestloginActionPerformed
        // TODO add your handling code here:
        text_username.setText("");
        text_password.setText("");
        CardLayout cardLayout = (CardLayout) rightpanel.getLayout();
        GuestWorkAreaJPanel gwajp = new GuestWorkAreaJPanel(rightpanel,system, dB4OUtil);
        rightpanel.add("GuestWorkAreaJPanel",gwajp);
        cardLayout.next(rightpanel);
    }//GEN-LAST:event_btn_guestloginActionPerformed

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guestlogin;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
